project:
  type: website
  output-dir: docs

website:
  title: "Megan Hessel"
  navbar:
    right:
      - href: index.qmd
        text: Home
    # - about.qmd
    # - href: resources.qmd
  # text: Resources 
        
format:
  html:
    theme: cosmo 
    css: styles.css
    toc: true
    page-layout: article



