project:
  type: website
  output-dir: docs

website:
  title: "Megan Hessel"
  favicon: images/My_logo_simplify2.png
  navbar:
    title: false
    logo: images/My_logo_simplify2.png
    logo-alt: the name megan hessel with a blog
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - posts.qmd
      # - href: resources.qmd
      #  text: Resources 
      - icon: github
        href: https://github.com/meganhessel
  page-footer: 
    left: Copyright 2025, Megan Hessel
    right: images/MY_logo.png
        
format:
  html:
    theme: styles.scss 
    toc: true
    page-layout: article
    mainfont: Lora



