project:
  type: website
  output-dir: docs

website:
  navbar:
    title: "Megan Hessel"
    logo: "My_logo.png"
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resources.qmd
        text: Resources 
        
format:
  html:
    theme: cosmo 
    css: styles.css
    toc: true
    page-layout: article



