---
title: "About"
---

## Education

Motivated by a deep interest in environmental conservation, I graduated from the University of Tampa with a B.S. in Environmental Studies and minors in Marine Science and Sustainability. I went on to earn a Masters of Environmental Data Science (MEDS) from UCSB’s Bren School of Environmental Science & Management, where I developed expertise in statistical modeling, programming, and data visualization.

## Professional Experience

I interned for **Sarasota County Government** in the Parks and Recreational department. In this position, I designed environmental education programs that raised awareness and helped communities reconnect with the natural world. This included children marine science camps, fishing expeditions, beach clean-ups, invasive plant removal, native tree planting, and seagrass and Florida Scrub Jay surveys.

During undergrad, I participated in multiple research projects. I was the lab manager of the **Spatial Ecology Lab (SEL)**, where I conducted research on the diets, spatial distribution, and age and growth patterns of both native and invasive fish species though stomach dissections, external floy tagging, and otolith examination. Partnering with the Gulf of Mexico Fishery Management Council, I used fishing tournament records to analyze and map the significant changes in King Mackerel populations spatially and over time. To further environmental education, I designed the annual Invasive Cichlid Kids Fishing Tournament (ICK). The lab now hosts this day camp for about fifty kids in Tampa Bay to teach about habitat degradation and sustainable practices every year. 

In my final years of undergrad, I became interested in public health. Therefore, I joined a public health vaping project, called **Vaping On Campus (VOC)**, where I administered surveys, interviews, and focus groups to study college students’ perceptions of vaping to create effective and targeted vaping cessation programs. Here, Dr. Martinasek and I published *A Review of Interventions Centered on Young Adults Framed in the Socio-Ecological Model* (2025).

At the University of Tampa, I also served as a **teaching assistant** for biostatistics, geographic information systems (GIS), and environmental microbiology, which sparked my initial interest in data science and teaching. I mentored students through rigorous software (SPSS and ESRI ArcGIS Pro) and provided instructional support by leading lab and discussion sessions.

## For Fun 

I love to be outside! I am an active person, who prefers to be surfing, sports, running, and swimming. I grew up water skiing and playing soccer. Today, I still play pick-up soccer, and I am training for a triathlon. Furthermore, I love traveling - especially anything near the water. Last summer, I spent a month backpacking around South Europe, such as France, Italy, Greece, and Croatia. Previously, I have sailed around the Caribbean. All to say, I love being outside, near the water, and exploring. If anyone has any advise or stories, I am all ears! 

## Passions

As many environmental scientists, my love for the outside and nature inspired my passion for environmental studies. As a multi-faceted and multi-disciplinary field, finding my niche took time. I always gravitated towards statistics, math, and map making. But once I realized data has the power to drive meaningful change, I knew my path. Data-driven decisions is the most effective way to combat climate change. Therefore, good data collection and analysis matters. With my Master of Environmental Data Science from UCSB and a background in research, I want to use data to promote action and construct a more sustainable future. I want to create innovative environmental solutions that make a lasting difference in the world. 
